### ISSUE TITLE
Char creator

### ISSUE THREAD

**Issue by AndrewCMD** [UNTAMEDHero/uHRP-RAGEMP#1]
when i go to create a char nothing is coming up to create my char...

**Comment by UNTAMEDHero** [comment]
Fixed, error was here -> https://github.com/UNTAMEDHero/uHRP-RAGEMP/commit/edfa28792741543d523226db7b862d2a6006b0c9#diff-0ddef3f71e18f0f8ce5c788ca82cec17

If by any chance you get reac source full, you can share with us!

Even for other fixes -> make a pull.
