### ISSUE TITLE
Clothing Shop , Fuel System

### ISSUE THREAD

**Issue by AndrewCMD** [UNTAMEDHero/uHRP-RAGEMP#2]
Clothing Shops dosent work , it shows fitting all the time.

Fuel System , i can't refill at the gas station.

as an owner of an shop you cant sell it ,
you can't  price items and can't set Owners.

**Comment by AndrewCMD** [comment]
and as police i can't buy weapons

**Comment by UNTAMEDHero** [comment]
Fixed, but now i'm dealing with a bug in inventory so watch this out.

Known bug aswell PD and other Factions, where you are unable to get weapons.
I'll fix them asap.

**Comment by AndrewCMD** [comment]
thanks for the fast fix :D
